import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { ModalProvider } from '@/provider/modal-provider'
import ToastProvider from '@/provider/toast-provider'
import { PayPalScriptProvider} from "@paypal/react-paypal-js"
import { ThemeProvider } from '@/provider/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ecommerce Admin Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const initialOptions = {
  //   clientId: "AVD4_P5KrTNuFILTFV-yjnv8nqVm29iZQjGxPyprDoCQH6X4G9AzS3Kow1UsfyB_qzQnmyhqcth4pDWE",
  //   currency: "USD",
  //   intent: "capture",
  // };

  return (
    <ClerkProvider>
      {/* <PayPalScriptProvider options={initialOptions}> */}
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider  attribute="class" defaultTheme="system" enableSystem>
            <ToastProvider />
            <ModalProvider />
            {children}
          </ThemeProvider>
        </body>
      </html>
      {/* </PayPalScriptProvider> */}
    </ClerkProvider>
  )
}
